[package]
name = "cassandra_macro"
version = "0.1.0"
authors = ["NunuM <nuno@nunum.me>"]
edition = "2018"
description = "Generate CQL for cassandra table creation from Rust structs"
homepage = "https://github.com/NunuM/rust-cassandra-tables-from-rust-struct-macro"
repository = "https://github.com/NunuM/rust-cassandra-tables-from-rust-struct-macro"
keywords = ["cassandra", "api", "migrations", "automation", "cql", "tables"]

[dependencies]
