[package]
name = "cassandra_macro"
version = "0.1.0"
authors = ["nuno <1140358@isep.ipp.pt>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
